### ISSUE TITLE
Schematic Builder/Saver Issue details

### ISSUE THREAD

**Issue by KrunkerPremium** [hollow-cube/common#41]
Step by Step

1)  Saving the schematic using

                case SAVE -> {
                    PlayerClipboard playerClipboard = clipboard.get(p.getUuid());
                    Point a = playerClipboard.getPos1().add(0,-1,0);
                    Point b = playerClipboard.getPos2().add(0,-1,0);
                    for (int x = Math.min(a.blockX(), b.blockX()); x <= Math.max(a.blockX(), b.blockX()); x++) {
                        for (int y = Math.min(a.blockY(), b.blockY()); y <= Math.max(a.blockY(), b.blockY()); y++) {
                            for (int z = Math.min(a.blockZ(), b.blockZ()); z <= Math.max(a.blockZ(), b.blockZ()); z++) {
                                Pos pos = new Pos(x, y, z);
                                playerClipboard.getBuilder().addBlock(pos, p.getInstance().getBlock(pos));
                            }
                        }
                    }

                    Pos offset = new Pos(a.blockX()-p.getPosition().blockX(),a.blockY()-p.getPosition().blockY(),a.blockZ()-p.getPosition().blockZ());
                    playerClipboard.getBuilder().setOffset(offset);
                    p.sendMessage("Offset = " +offset);

                    Schematic schematic = playerClipboard.getBuilder().toSchematic();
                    try {
                        File file = new File("./schematics/test.schem");
                        if (file.exists()){
                            if (file.delete()){
                                p.sendMessage("delete file");
                            }else {
                                p.sendMessage("did not delete file");
                            }
                        }
                        file.createNewFile();
                        SchematicWriter.write(schematic,file.toPath());
                        p.sendMessage("Success");
                    } catch (IOException e) {
                        p.sendMessage("Fail");
                        throw new RuntimeException(e);
                    }
                }

                        
2) Load the schematic

                case LOAD -> {
                    File file = new File("./schematics/test.schem");
                    try {
                        SchematicReader.read(file.toPath()).build(Rotation.NONE,null).apply(p.getInstance(), p.getPosition().blockX(),p.getPosition().blockY(),p.getPosition().blockZ(),null);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }

3) Get this error Caused by: java.lang.NullPointerException: Missing required field 'Width'

[Ms-Tick-0] [00:02:22] (CommandParserImpl$ValidExecutableCmd.execute) - ERROR - An exception was encountered while executing command: schem load: java.lang.RuntimeException: Invalid schematic file
	at schem.SchematicReader.read(SchematicReader.java:79)
	at schem.SchematicReader.read(SchematicReader.java:29)
	at me.premium.command.SchematicCommand.lambda$new$1(SchematicCommand.java:117)
	at net.minestom.server.command.CommandParserImpl$ValidExecutableCmd.execute(CommandParserImpl.java:280)
	at net.minestom.server.command.CommandManager.execute(CommandManager.java:113)
	at net.minestom.server.listener.ChatMessageListener.commandChatListener(ChatMessageListener.java:28)
	at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:90)
	at net.minestom.server.entity.Player.lambda$interpretPacketQueue$16(Player.java:1802)
	at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:312)
	at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:1802)
	at net.minestom.server.entity.Player.update(Player.java:345)
	at net.minestom.server.entity.Entity.tick(Entity.java:541)
	at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
	at net.minestom.server.thread.TickThread.run(TickThread.java:41)
Caused by: java.lang.NullPointerException: Missing required field 'Width'
	at net.minestom.server.utils.validate.Check.notNull(Check.java:22)
	at schem.SchematicReader.read(SchematicReader.java:39)
	... 13 more

**Comment by mworzala** [comment]
Confusing, I have been using SchematicBuilder quite a bit. I will take a look, thanks

**Comment by KrunkerPremium** [comment]
in the code I provided did I use it wrong or?

could you show me an example of your working code for ref?

thank you

**Comment by mworzala** [comment]
I was just thinking of schematic builder, I did not have a valid use of `SchematicWriter` and there was indeed a bug. It should be fixed now.

**Comment by KrunkerPremium** [comment]
Awesome!!! good job bro.
